### ISSUE TITLE
ValueError: Passed db_path does not exist!

### ISSUE THREAD

**Issue by karmelyoei** [mattlyon93/face-comparison#7]
I am facing this issue how could i possible fix this

**Comment by mattlyon93** [comment]
I'm not sure if this is an error pertaining to the `face-compare` module.
Could you paste the entirety of the error code please?

**Comment by karmelyoei** [comment]
raceback (most recent call last):
  File "compare_faces.py", line 8, in <module>
    result = DeepFace.find(image, image2)
....local/lib/python3.8/site-packages/deepface/DeepFace.py", line 722, in find
    raise ValueError("Passed db_path does not exist!")
ValueError: Passed db_path does not exist!

**Comment by mattlyon93** [comment]
This isn't an error raised by this package.

```
File "compare_faces.py", line 8, in
result = DeepFace.find(image, image2)
```

This module does not use [DeepFace](https://github.com/serengil/deepface) at all, likely this is an error caused by another script with the name `compare_faces.py`. If you want to use this module module I recommend using a new python virtual environment.
